version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data1
      - ./background/initscripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=root
      - POSTGRES_DB=parking_reservation